### ISSUE TITLE
trim breaks includegraphics

### ISSUE THREAD

**Issue by ju-w** [rolfn/overpic#4]
Hello!

When I use `trim`, other includegraphics will be scaled weirdly.

## without trim

```latex
\begin{overpic}[scale=0.5, width=.6\linewidth,frame=2\fboxrule,grid,]{{images/pika.png}}
    \put(20, 10){\includegraphics[width=10mm,height=10mm,frame=2\fboxrule]{images/arr.png}}
\end{overpic}
```
![overpic_good](https://github.com/rolfn/overpic/assets/22564375/b5d1a467-ddd9-4907-88a5-0084a6dce63a)

## with trim

```latex
\begin{overpic}[scale=0.5, width=.6\linewidth,frame=2\fboxrule,grid,trim={10mm 20mm 30mm 40mm}]{{images/pika.png}}
    \put(20, 10){\includegraphics[width=10mm,height=10mm,frame=2\fboxrule]{images/arr.png}}
\end{overpic}
```
![overpic_bug](https://github.com/rolfn/overpic/assets/22564375/fae8ebac-e8a3-4f9f-bbdf-c6cacb65e0f7)

**Comment by rolfn** [comment]
I can reproduce the error and will try to find a solution. But that could still take some time.

**Comment by rolfn** [comment]
I changed the code (new version 2.0), so hopefully the problem is fixed. Please test. 

I will upload the new version to CTAN soon.

Some notes about your tests:

* There is no key named `frame`.
*  Double curly brackets around the filename parameter are unnecessary.
*  The `clip` parameter is recommended together with `trim` or `viewport`.
