### ISSUE TITLE
Bug when using overpic with \frame{}?

### ISSUE THREAD

**Issue by MangoSister** [rolfn/overpic#8]
It seems like using overpic together with \frame{} produces a slight misalignment. An example can be found in this public overpic example on overleaf: https://www.overleaf.com/latex/examples/overpic-example/ycqxgvkntcjc (or https://github.com/delrocco/overpic-example). Notice the image has a small offset and the border by \frame{} does not fit tightly:
<img width="653" alt="Capture" src="https://github.com/user-attachments/assets/056226c1-700c-42a9-82d6-166fb1083e7d">

I am not 100% sure but I only noticed this after updating overpic to 2.1. The old pdf of this overleaf example also does not have this issue (presumably compiled using an old version of overpic). Any idea why could this happen? Thanks.

**Comment by rolfn** [comment]
I simplified the code in question as follows:

```latex
\listfiles
\documentclass{article}
\usepackage[permil]{overpic}

\begin{document}

\frame{
\begin{overpic}[width=0.6\textwidth]{example-image-a}%
  \put(20,600) {Salmon sashimi with sesame seeds and lemon}%
\end{overpic}
}

\end{document}
```

As you can see, the incorrect spacing between the image and the frame occurs here too. Older versions of overpic show the same behavior. The reason is that the end of the line after `\end{overpic}` is not commented out and thus has the effect of additional word spacing. Change

```latex
\end{overpic}
```

to

```latex
\end{overpic}%
```
